version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "daily"
  # Dependabot only updates hashicorp GHAs, external GHAs are managed by internal tooling (tsccr)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "hashicorp/*"
