issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - paralleltest
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - govet

run:
  # Prevent false positive timeouts in CI
  timeout: 5m
